name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    permissions: write-all

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: JDK 17をセットアップ
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: ビルド
      run: mvn -B package --file pom.xml
    - name: original-*.jarを削除
      run: rm DataPackPlugin/target/original-*.jar
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: 'DataPackPlugin/target/*.jar'
